export const enum ClassName {
    Lock = '_lock',
    Page = 'page',
    Container = 'container',
    Wrapper = 'wrapper',
    TabsContent = 'tabs-content',
    Tabs = 'tabs',
    Tab = 'tab',
    Button = 'button',
    List = 'list',
    Title = 'title',
    Form = 'form',
    Hidden = 'visually-hidden',
    Active = 'active',
    DropdownMenu = 'dropdown-menu',
    Crumbs = 'breadcrumbs',
    Section = 'section',
    Icon = 'icon',
    Checkbox = 'checkbox',
    Radiobutton = 'radiobutton',
}